### ISSUE TITLE
HDR Bundle references IPS AllergyIntolerance while HDR Composition references EPS AllergyIntolerance

### ISSUE THREAD

**Issue by CS-Olav** [hl7-eu/hdr#15]
[The profile for an HDR Bundle](https://build.fhir.org/ig/hl7-eu/hdr/StructureDefinition-bundle-eu-hdr.html) specifies entries for allergies and intolerances should adhere to [the IPS profile for AllergyIntolerance](https://build.fhir.org/ig/HL7/fhir-ips/StructureDefinition-AllergyIntolerance-uv-ips.html) whilst [the profile for the Composition describing the structure of this Bundle](https://build.fhir.org/ig/hl7-eu/hdr/StructureDefinition-composition-eu-hdr.html) specifies the section for allergies and intolerances should references AllergyIntolerances adhering to [the EU PS profile for this](https://build.fhir.org/ig/hl7-eu/hdr/StructureDefinition-allergyIntolerance-eu-eps.html). This seems inconsistent.

**Comment by gcangioli** [comment]
1) most part are still under development => I need to update the reference in the bundle
2) the EU PS profile is intended to comply with the IPS one so there are no conflicts

**Comment by CS-Olav** [comment]
> the EU PS profile is intended to comply with the IPS one so there are no conflicts
@gcangioli if you mean here that it shouldn't matter which profile is referenced because there aren't just no conflicts but the profiles are identical, shouldn't the European profile be deleted and the profile from IPS be referenced instead so the world can easily see this is the same?
